Pagination
wolox-training/dc-rails pull request #17
Opened 2017-08-11 18:00 UTC by dcarrilloWolox

## Summary ##
* I installed wor-pagination gem
## Trello Card ##
https://trello.com/c/Z7ScsqVM/34-agregar-paginaci%C3%B3n-a-index-de-book-y-tests

2017-08-14 13:26 UTC, Martum requested changes

2017-08-14 13:26 UTC, Martum commented on app/controllers/api/v1/users_controller.rb
> +      before_action :current_user
Why are you doing this??

2017-08-14 13:26 UTC, Martum commented on app/controllers/api_controller.rb
> +  before_action :current_user, :authenticate_request
Why did you remove `:set_locale`?

2017-08-14 13:26 UTC, Martum commented on spec/controllers/api/v1/users_controller_spec.rb
> +describe Api::V1::UsersController do
Its fine, but also use the pagination [helpers](https://github.com/Wolox/wor-paginate#test-helpers) included in the gem.

2017-08-14 13:46 UTC, Martum commented on app/controllers/api_controller.rb
> +  before_action :current_user, :authenticate_request
`I18n.locale = current_user&.locale || I18n.default_locale`

`!current_user.nil? && current_user.locale`

2017-08-14 16:47 UTC, dcarrilloWolox commented on app/controllers/api/v1/users_controller.rb
> +      before_action :current_user
my bad it was :set_locale, but i'll move this to apiController

2017-08-15 16:19 UTC, Martum approved these changes

2017-08-15 17:40 UTC, merged