Suggestion view
wolox-training/dc-rails pull request #21
Opened 2017-08-15 17:59 UTC by dcarrilloWolox

## Summary ##
* I create a new book suggestion view
## Trello card ##
https://trello.com/c/7mUhpXYf/28-crear-vista-para-crear-book-suggestions

2017-08-17 18:37 UTC, Martum requested changes

2017-08-17 18:37 UTC, Martum commented on app/controllers/book_suggestions_controller.rb
> +    suggestion_params = params.require(:book_suggestion).permit!
Its not a good practice use `.permit!` lets change it with strong params!

2017-08-17 18:37 UTC, Martum commented on app/controllers/book_suggestions_controller.rb
> +  def create
You are POSTing to this action via AJAX, move it to Api/V1

2017-08-17 18:37 UTC, Martum commented on app/views/book_suggestions/new.html.slim
> +    .on('ajax:success',
Add error handling! Nothing too fancy, just an error box displaying all the errors.

2017-08-17 18:37 UTC, Martum commented on app/controllers/book_suggestions_controller.rb
> +      render suggestion.errors
`render json: suggestion.errors.to_h`

2017-08-18 14:37 UTC, JessSaavedra requested changes

2017-08-18 14:37 UTC, JessSaavedra commented on app/assets/stylesheets/new_book_suggestion.scss
> +#suggestion-table {
Don't use ids in CSS (even though it's ok for grabbing an element in javascript). They have higher priority than simpler rules and that can cause trouble when adding new style to a component.

2017-08-18 14:37 UTC, JessSaavedra commented on app/views/book_suggestions/new.html.slim
> += form_with model: @suggestion, html: {class: ['flex-column', 'new-form'], id: 'suggestion-form'} do |f|
You can directly write `class: 'flex-column new-form'`

2017-08-18 14:37 UTC, JessSaavedra commented on app/views/book_suggestions/new.html.slim
> +javascript:
It's not recommended to mix rails code with javascript, let's move this to a separated file in app/assets/javascripts

2017-08-18 14:37 UTC, JessSaavedra commented on app/views/book_suggestions/new.html.slim
> +        console.log($('form').serializeArray().length);
Delete this console.log

2017-08-18 14:37 UTC, JessSaavedra commented on app/views/book_suggestions/new.html.slim
> +      $('#suggestion-table').css("display", "block");
With jquery, you can use `$('#suggestion-table').toggle()` which alternates between showing and hiding the element. Good thing about it is that you can use it for both hiding and showing and that you are not coupled to knowing which is the exact display of the element before hiding it (unless you actually want to change it to be differente from original CSS, but I think it's not a common case :stuck_out_tongue: )

2017-08-18 14:37 UTC, JessSaavedra commented on app/views/book_suggestions/new.html.slim
> +    var addSuggestion = function(suggestions) {
I think it's confusing to have this parameter called suggestions, wouldn't it be just a suggestion? Maybe you can name this suggestionFields or something like that? :thinking:

2017-08-18 16:19 UTC, Martum commented on app/controllers/book_suggestions_controller.rb
> +  def create
`skip_before_action :current_user, :authenticate`

2017-08-25 14:26 UTC, merged